name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

# ...existing code...
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  provider: ^6.1.1
  # Firebase
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  # UI & Animations
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  lottie: ^3.3.2
  # Utilities
  intl: ^0.20.2
  image_picker: ^1.0.4
  uuid: ^4.2.1
# ...existing code...

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/noto-sans-latin-400-normal.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/noto-sans-latin-700-normal.ttf
          weight: 700