// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9z6E0_B_9jfEtIVqV5Cj6-3vLjv_dwn8',
    appId: '1:676395979911:web:494523396580b065481422',
    messagingSenderId: '676395979911',
    projectId: 'bluemoon---delivery-app',
    authDomain: 'bluemoon---delivery-app.firebaseapp.com',
    storageBucket: 'bluemoon---delivery-app.firebasestorage.app',
    measurementId: 'G-6JSQE3XXEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCckldXz0eQbTHvm3zYGnQl2wvHxFX1tYg',
    appId: '1:676395979911:android:208179180e656bce481422',
    messagingSenderId: '676395979911',
    projectId: 'bluemoon---delivery-app',
    storageBucket: 'bluemoon---delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvOdEI2K9MCJgwTldpvqNCsscBzm1O9n8',
    appId: '1:676395979911:ios:7a7404f2fcb3d4ba481422',
    messagingSenderId: '676395979911',
    projectId: 'bluemoon---delivery-app',
    storageBucket: 'bluemoon---delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvOdEI2K9MCJgwTldpvqNCsscBzm1O9n8',
    appId: '1:676395979911:ios:7a7404f2fcb3d4ba481422',
    messagingSenderId: '676395979911',
    projectId: 'bluemoon---delivery-app',
    storageBucket: 'bluemoon---delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9z6E0_B_9jfEtIVqV5Cj6-3vLjv_dwn8',
    appId: '1:676395979911:web:5e4f44fa31f0c9de481422',
    messagingSenderId: '676395979911',
    projectId: 'bluemoon---delivery-app',
    authDomain: 'bluemoon---delivery-app.firebaseapp.com',
    storageBucket: 'bluemoon---delivery-app.firebasestorage.app',
    measurementId: 'G-SXKJY2ZGQW',
  );
}
